### ISSUE TITLE
supabaseAuthClient.auth.getUser not working on v2.42.5

### ISSUE THREAD

**Issue by yunpaik** [supabase/supabase-js#1025] opened 2024-04-23 07:05 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When calling `await supabaseAuthClient.auth.getUser()` in the edge function, the following error is returned even though the correct jwt token was provided.

```
{
  data: { user: null },
  error: AuthSessionMissingError: Auth session missing!
    at https://esm.sh/v135/@supabase/auth-js@2.63.1/esnext/auth-js.mjs:2:29430
    at _._useSession (https://esm.sh/v135/@supabase/auth-js@2.63.1/esnext/auth-js.mjs:2:27513)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async _._getUser (https://esm.sh/v135/@supabase/auth-js@2.63.1/esnext/auth-js.mjs:2:29103)
    at async https://esm.sh/v135/@supabase/auth-js@2.63.1/esnext/auth-js.mjs:2:28966 {
    __isAuthError: true,
    name: "AuthSessionMissingError",
    status: 400,
    code: undefined
  }
}
```

This issue only happens on v2.42.5. The same code works perfectly fine on v.2.42.4.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `await supabaseAuthClient.auth.getUser()` in the edge function with correct jwt token

## Expected behavior

I should be able to get user session without any issue

**Comment by christophemenager** [comment] 2024-04-23 14:17
> I confirm I have searched the [Docs](https://docs.supabase.com/), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com/).

Really? :) 

Duplicate of:
- https://github.com/supabase/supabase-js/issues/1024
- https://github.com/supabase/auth-js/issues/881

**Comment by GaryAustin1** [comment] 2024-04-23 15:11
Going to leave this open for now as for some reason the fix made in auth-js has not been released here in supabase-js.

This issue is impacting users of edge functions still currently.

**Comment by kangmingtay** [comment] 2024-04-25 17:30
We've made the fix in #1029 so it should be available in supabase-js v2.64.1, thanks for reporting this!

**Closed by kangmingtay** 2024-04-25 17:30 UTC
Labels: bug

**Comment by NickG-NZ** [comment] 2024-05-16 22:19
> We've made the fix in #1029 so it should be available in supabase-js v2.42.7, thanks for reporting this!

@kangmingtay 
Still getting this issue after upgrading from 2.38.4 to 2.43.2.

I'm actually getting it in a NextJS route-handler. But seems to be essentially the same problem, although the solution of explicitly passing the JWT isn't relevant given the supabase ssr client uses the cookies...

**Comment by Tynopia** [comment] 2024-05-26 19:48
> > We've made the fix in #1029 so it should be available in supabase-js v2.42.7, thanks for reporting this!
> 
> @kangmingtay Still getting this issue (caused by upgrading from 2.38.4 to 2.43.2)
> 
> I'm actually getting it in a NextJS route-handler. But seems to be essentially the same problem, although the solution of explicitly passing the JWT isn't relevant given the supabase ssr client uses cookies.
> 
> Can make a separate issue if needed

I think i have the same issue

**Comment by ThisIsRahmat** [comment] 2024-06-02 02:22
I also have this same issue with my web app. My web app is  builtwith Remix framework 

I only see the error:` AuthSessionMissingError: Auth session missing!` when I try to get my user using: `supabase.auth.getUser();` I am able to sign up and login successfully but when I go to fetch the newly logged in user, all I get is null.

Additionally I am using supabase from the sever side, supabase/ssr and not supabase/js

**Comment by NickG-NZ** [comment] 2024-06-02 02:49
I've created a new issue here #1202

**Comment by sbhatm1213** [comment] 2024-10-13 15:45
Facing this error still `AuthSessionMissingError: Auth session missing!` at http://localhost:3000/static/js/bundle.js:79331:20

Steps followed -
(1) Add Client ID and Secret on Supabase Google Auth Provider - Done
(2) Add Javascript origin - Done - http://localhost:3000/
(3) Add Redirect URI - Done - http://localhost:3000/auth/v1/callback and https://my-domain.supabase.co/auth/v1/callback
(4) Add code for `onAuthStateChange` - Done
(5) Try using `const { data: { session } } = await supabase.auth.getSession()`  - Done - Doesn't work
(6) Try using `const { data: { user } } = await supabase.auth.getUser()` - Done - Doesn't work 
(7) Try with different `gotrue-js` version - Done - "@supabase/supabase-js": {
      "@supabase/gotrue-js": "2.43.1"
    }
(8) Try on Firefox - Done - This works fine , so on Chrome is the problem

Same issue even with Azure

Although login happens, cannot get the session/user
