### ISSUE TITLE
Instantiating supabase from unpkg stopped working

### ISSUE THREAD

**Issue by richcorbs** [supabase/supabase-js#120] opened 2021-01-16 22:34 UTC
# Bug report

Instantiating supabase from unpkg stopped working.

## Describe the bug

Below results in `Cannot read 'createClient' of undefined`. It used to work.

```
<script src="https://unpkg.com/@supabase/supabase-js"></script>
<script>
    const supabaseUrl = 'my supabase url'
    const supabaseAnonKey = 'my anon key'
    var supabase = supabase.createClient(supabaseUrl, supabaseAnonKey)
</script>
```

## Expected behavior

It is expected that the above code or a similar construct will work. Maybe the API changed?

**Comment by inian** [comment] 2021-01-18 17:51
Hi @richcorbs. this is a duplicate of https://github.com/supabase/supabase-js/issues/113#issuecomment-758777176. Tracking it in that issue

**Closed by inian** 2021-01-18 17:51 UTC
Labels: bug
