### ISSUE TITLE
HPE_INVALID_CONSTANT when running locally

### ISSUE THREAD

**Issue by 72L** [supabase/supabase-js#737] opened 2023-03-27 13:57 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`HPE_INVALID_CONSTANT` error

```
{"message":"FetchError: request to http://localhost:54321/rest/v1/memberships?select=*&limit=10 failed, reason: Parse Error: Expected HTTP/","details":"","hint":"","code":"HPE_INVALID_CONSTANT"}
```

## To Reproduce

1. `supabase start`
2. run: ```await supabase
    .from(TABLES.MEMBERSHIPS)
    .select()
    .limit(10)```
3. get this error: ```{"message":"FetchError: request to http://localhost:54321/rest/v1/memberships?select=*&limit=10 failed, reason: Parse Error: Expected HTTP/","details":"","hint":"","code":"HPE_INVALID_CONSTANT"}```

## Expected behavior

There should be no error.

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: 2.12.1
- Version of Node.js: v16.15.1

## Additional context

It was working the last time I was using this and nothing in my code base has changed.

**Comment by 72L** [comment] 2023-03-27 14:16
I made the request with python and it works fine:
```
resp = requests.get(
    'http://localhost:54321/rest/v1/memberships?select=*&limit=10', 
    headers={
        'Authorization': 'Bearer <service_role key>',
        'apikey': '<service_role key>'
    }
)
```

`resp.text` gives the json text as expected

**Comment by soedirgo** [comment] 2023-04-06 06:08
This might've been a bug in either [node-fetch](https://github.com/node-fetch/node-fetch) or Node.js. I'm not able to reproduce this so I'll close this for now - feel free to create another issue if it reappears.

**Closed by soedirgo** 2023-04-06 06:08 UTC
Labels: bug
