### ISSUE TITLE
Compilation errors with TypeScript

### ISSUE THREAD

**Issue by ohnv** [supabase/supabase-js#96] opened 2020-12-09 13:28 UTC
# Improve documentation

## Link 

https://supabase.io/docs/client/installing

## Describe the problem

Hi, I wasn't sure whether to file this as a bug report or a documentation issue as I am not sure which it is.

Typescript and Node really aren't my forte so sorry if this is something basic, but after running the install steps at the above link and then following the createClient example (https://supabase.io/docs/client/initializing) I run into the following compilation errors while compiling with Typescript:

> node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.d.ts:19:29 - error TS2304: Cannot find name 'Storage'.
> 19     protected localStorage: Storage;

> node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.d.ts:38:24 - error TS2304: Cannot find name 'Storage'.
> 38         localStorage?: Storage;

> node_modules/@supabase/postgrest-js/dist/main/lib/types.d.ts:33:20 - error TS2304: Cannot find name 'URL'.
> 33     protected url: URL;

> node_modules/@supabase/supabase-js/dist/main/lib/SupabaseAuthClient.d.ts:11:24 - error TS2304: Cannot find name 'Storage'.
> 11         localStorage?: Storage;

> node_modules/@supabase/supabase-js/dist/main/lib/types.d.ts:27:20 - error TS2304: Cannot find name 'Storage'.
27     localStorage?: Storage;

## Describe the improvement

If there are additional steps required to work with Typescript, it would be nice if the documentation provided direction. Or if it already exists, maybe just a link on the installation page to the Typescript-specific documentation.

Thanks :-)

**Comment by kiwicopple** [comment] 2020-12-10 00:20
Hi @TheTrainor - this looks like it was due to some missing exports on our side.

@calendee fixed it here: https://github.com/supabase/supabase-js/issues/97. Can you try to instlall the latest supabase version?

`npm install @supabase/supabase@latest` 

this should bump it to `v1.1.0`

**Comment by calendee** [comment] 2020-12-10 01:55
Unfortunately, I can't reproduce the problem even when I checkout the previous releases and build them. Hopefully I'm just doing something wrong though.

@TheTrainor Did updating the `@supabase/supabase` package solve the problem? 🤞

If not, can you create a public repo that demonstrates the problem?

Thanks!

**Comment by TheTrainor** [comment] 2020-12-10 10:41
Thanks for the help guys. 

It turned out the problem was my tsconfig.json file:

```
"compilerOptions": {
      "experimentalDecorators": true,
      "target": "ES2015",
      "module": "commonjs",
      "outDir": "../build", 
      "noEmit": false,
      "sourceMap": true,
      "lib": [ //---
        "ES6"  // Removing these 3 lines fixed the problem.
      ]        //---
    },
```

Thanks for the quick response @kiwicopple and @calendee. I am looking forward to trying out Supabase properly.

**Comment by ChronSyn** [comment] 2021-04-02 21:14
Sorry for reopening this issue, but for anyone else having issues with this, ensure you have the following in your `tsconfig.json`

```
{
  "compilerOptions": {
    "skipLibCheck": true
  },
}
```

**Comment by inian** [comment] 2021-05-13 07:52
I think we should fix the type errors here. `skipLibCheck` just helps sidestep the issue

**Comment by inian** [comment] 2021-05-17 12:28
Not sure if we can fix this issue in the library itself. I fixed this by adding the "DOM" to tsconfig lib attribute in the project consuming supabase-js. 
The AWS SDK seems to have the [same issue](https://github.com/aws/aws-sdk-js-v3/issues/2085) and they recommend adding dom types to your tsconfig file.

**Comment by soedirgo** [comment] 2021-08-11 16:51
Doesn't seem like there's a better alternative to adding `DOM` to `lib`, so closing this for now.

**Closed by soedirgo** 2021-08-11 16:51 UTC
Labels: documentation
